CREATE TABLE EVENT
(
  EVENT_UID      VARCHAR(100) NOT NULL COMMENT '이벤트게시판UID',
  EVENT_FILE     VARCHAR(100) NULL     COMMENT '이벤트첨부파일',
  EVENT_TITLE    VARCHAR(100) NOT NULL COMMENT '이벤트제목',
  EVENT_DATE     VARCHAR(100) NOT NULL COMMENT '이벤트작성일',
  EVENT_DATETIME VARCHAR(100) NULL     COMMENT '이벤트기간',
  EVENT_CONTENT  VARCHAR(100) NOT NULL COMMENT '이벤트내용',
  PRIMARY KEY (EVENT_UID)
) COMMENT '이벤트게시판';

CREATE TABLE NOTICE
(
  NOTICE_UID     VARCHAR(100) NOT NULL COMMENT '공지게시판UID',
  NOTICE_DATE    VARCHAR(100) NOT NULL COMMENT '공지작성일',
  NOTICE_WRITER  VARCHAR(100) NOT NULL COMMENT '공지작성자',
  NOTICE_TITLE   VARCHAR(100) NOT NULL COMMENT '공지제목',
  NOTICE_CONTENT VARCHAR(100) NOT NULL COMMENT '공지내용',
  NOTICE_FILE    VARCHAR(100) NULL     COMMENT '공지첨부파일',
  PRIMARY KEY (NOTICE_UID)
) COMMENT '공지게시판';

CREATE TABLE QNA
(
  QNA_UID       VARCHAR(100)  NOT NULL COMMENT '문의게시판UID',
  PRODUCT_CODE  VARCHAR(100)  NOT NULL COMMENT '상품코드',
  QNA_TITLE     VARCHAR(100)  NOT NULL COMMENT '문의제목',
  QNA_WRITER    VARCHAR(100)  NOT NULL COMMENT '문의작성자',
  QNA_CONTENT   VARCHAR(100) NOT NULL COMMENT '문의내용',
  QNA_DATE      VARCHAR(100)  NOT NULL COMMENT '문의작성일',
  ANSWER_STATUS VARCHAR(100)  NOT NULL COMMENT '답변상태',
  QNA_ANSWER    VARCHAR(100)  NULL     COMMENT '문의답변',
  PRIMARY KEY (QNA_UID)
) COMMENT '문의게시판';

CREATE TABLE REVIEW
(
  REVIEW_UID     VARCHAR(100) NOT NULL COMMENT '리뷰UID',
  PRODUCT_CODE   VARCHAR(100) NOT NULL COMMENT '상품코드',
  REVIEW_TITLE   VARCHAR(100) NOT NULL COMMENT '리뷰제목',
  REVIEW_WRITER  VARCHAR(100) NOT NULL COMMENT '리뷰작성자',
  REVIEW_SCOPE   INTEGER      NOT NULL COMMENT '리뷰별점',
  REVIEW_DATE    VARCHAR(100) NULL     COMMENT '리뷰작성일',
  REVIEW_CONTENT VARCHAR(100) NULL     COMMENT '리뷰내용',
  PRIMARY KEY (REVIEW_UID)
) COMMENT '리뷰';

CREATE TABLE STORE
(
  STORE_UID  VARCHAR(100) NOT NULL COMMENT '판매처UID',
  STORE_NAME VARCHAR(100) NOT NULL COMMENT '판매처이름',
  SOTRE_NO   VARCHAR(100) NOT NULL COMMENT '판매처사업자번호',
  SOTRE_CEO  VARCHAR(100) NOT NULL COMMENT '판매처대표자',
  PRIMARY KEY (STORE_UID)
) COMMENT '판매처';

CREATE TABLE USERS
(
  USER_UID       VARCHAR(100) NOT NULL COMMENT '회원아이디',
  USER_PASSWORD  VARCHAR(100) NOT NULL COMMENT '회원비밀번호',
  USER_NAME      VARCHAR(100) NOT NULL COMMENT '회원이름',
  USER_BIRTH     VARCHAR(100) NOT NULL COMMENT '회원생년월일',
  USER_GENDER    VARCHAR(100) NOT NULL COMMENT '회원성별',
  USER_PHONE     VARCHAR(100) NOT NULL COMMENT '회원전화번호',
  USER_AUTHORITY VARCHAR(100) NOT NULL COMMENT '회원권한',
  PRIMARY KEY (USER_UID)
) COMMENT '회원들';

CREATE TABLE CHANGEINFO
(
  ID_UID         VARCHAR(100) NOT NULL COMMENT '아이디UID',
  ID             VARCHAR(100) NULL     COMMENT '아이디',
  PASSWORD       VARCHAR(100) NULL     COMMENT '비밀번호',
  CHANGEPASSWORD VARCHAR(100) NULL     COMMENT '변경할비밀번호',
  NAME           VARCHAR(100) NULL     COMMENT '이름',
  BIRTH          VARCHAR(100) NULL     COMMENT '생년월일',
  GENDER         VARCHAR(100) NULL     COMMENT '성별',
  PHONE          VARCHAR(100) NULL     COMMENT '휴대폰',
  PRIMARY KEY (ID_UID)
);

CREATE TABLE EVENT_CONTENT
(
  EVENT_CONTENT_UID VARCHAR(100) NOT NULL COMMENT 'ID',
  EVENT_TITLE       VARCHAR(100) NOT NULL COMMENT '이벤트 제목',
  EVENT_CONTENT     VARCHAR(100) NOT NULL COMMENT '이벤트 내용',
  EVENT_DATE        VARCHAR(100) NOT NULL COMMENT '이벤트 날짜',
  PRIMARY KEY (EVENT_CONTENT_UID)
) COMMENT '이벤트 내용';

CREATE TABLE EVENT
(
  EVENT_UID   VARCHAR(100) NOT NULL COMMENT 'ID',
  EVENT_TITLE VARCHAR(100) NOT NULL COMMENT '이벤트 제목',
  EVENT_DATE  VARCHAR(100) NOT NULL COMMENT '이벤트 날짜',
  PRIMARY KEY (EVENT_UID)
) COMMENT '이벤트';

CREATE TABLE ACCOUNT
(
  UNIQUE_ID VARCHAR(100) NOT NULL COMMENT '아이디',
  PASSWORD  VARCHAR(100) NOT NULL COMMENT '비밀번호',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '계정';

CREATE TABLE MYPAGE
(
  ID_UID                      NOT NULL,
  WISHLIST       VARCHAR(100) NULL     COMMENT '찜한상품',
  QNA            VARCHAR(100) NULL     COMMENT '문의내역',
  REVIEW         VARCHAR(100) NULL     COMMENT '내가쓴리뷰',
  USEABLE_COUPON VARCHAR(100) NULL     COMMENT '사용가능한쿠폰',
  PRIMARY KEY (ID_UID)
) COMMENT '마이페이지';

CREATE TABLE NOTICE_CONTENT
(
  NOTICE_CONTENT_UID VARCHAR(100) NOT NULL COMMENT 'ID',
  NOTICE_TITLE       VARCHAR(100) NOT NULL COMMENT '공지사항 제목',
  NOTICE_CONTENT     VARCHAR(100) NOT NULL COMMENT '공지사항 내용',
  NOTICE_DATE        VARCHAR(100) NOT NULL COMMENT '공지사항 작성일',
  PRIMARY KEY (NOTICE_CONTENT_UID)
) COMMENT '공지사항 내용';

CREATE TABLE NOTICE
(
  NOTICE_UID    VARCHAR(100) NOT NULL COMMENT 'ID',
  NOTICE_NO     INT          NOT NULL COMMENT '공지사항 번호',
  NOTICE_TITLE  VARCHAR(100) NOT NULL COMMENT '공지사항 제목',
  NOTICE_DATE   VARCHAR(100) NOT NULL COMMENT '공지사항 작성일',
  NOTICE_SEARCH VARCHAR(100) NULL     COMMENT '공지사항 검색',
  PRIMARY KEY (NOTICE_UID)
) COMMENT '공지사항';

CREATE TABLE QUESTIONS
(
  QUESTIONS_UID VARCHAR(100) NOT NULL COMMENT 'ID',
  QUESTION      VARCHAR(100) NOT NULL COMMENT '질문',
  ANSWER        VARCHAR(100) NOT NULL COMMENT '답',
  SEARCH        VARCHAR(100) NULL     COMMENT '검색',
  PRIMARY KEY (QUESTIONS_UID)
) COMMENT '자주하는 질문';

CREATE TABLE QNA
(
  QNA_UID   INTEGER      NOT NULL,
  QNA_NO    INTEGER      NULL     COMMENT 'Q_A번호',
  QNA_TITLE VARCHAR(100) NULL     COMMENT 'Q_A제목',
  QNA_TYPE  VARCHAR(100) NULL     COMMENT 'Q_A구분',
  PRIMARY KEY (QNA_UID)
);

CREATE TABLE USER
(
  UNIQUE_ID VARCHAR(100) NOT NULL COMMENT '아이디',
  PASSWORD  VARCHAR(100) NOT NULL COMMENT '비밀번호',
  NAME      VARCHAR(100) NOT NULL COMMENT '이름',
  BIRTH     VARCHAR(100) NOT NULL COMMENT '생년월일',
  GENDER    VARCHAR(100) NOT NULL COMMENT '성별',
  PHONE     VARCHAR(100) NOT NULL COMMENT '전화번호',
  AUTHORITY VARCHAR(100) NOT NULL COMMENT '권한',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '회원';

CREATE TABLE WINE
(
  WINE_UID            VARCHAR(100) NOT NULL COMMENT '와인UID',
  WINE_NAME           VARCHAR(100) NOT NULL COMMENT '와인명',
  WINE_NAME_EN        VARCHAR(100) NOT NULL COMMENT '와인명_영문',
  WINE_SCOPE          VARCHAR(100) NOT NULL COMMENT '와인별점',
  WINE_COMPANY        VARCHAR(100) NOT NULL COMMENT '와인회사',
  WINE_VARIETY        VARCHAR(100) NOT NULL COMMENT '와인품종',
  WINE_COUNTRY        VARCHAR(100) NOT NULL COMMENT '와인나라',
  WINE_REGION         VARCHAR(100) NOT NULL COMMENT '와인생산지역',
  WINE_TYPE           VARCHAR(100) NOT NULL COMMENT '와인종류',
  WINE_ALCOHOL_DEGREE VARCHAR(100) NOT NULL COMMENT '와인도수',
  WINE_PRICE          VARCHAR(100) NOT NULL COMMENT '와인가격',
  WINE_STORE          VARCHAR(100) NOT NULL COMMENT '와인판매처',
  WINE_IMAGE          VARCHAR(100) NOT NULL COMMENT '와인이미지',
  WINE_FILE           VARCHAR(100) NOT NULL COMMENT '와인상세파일',
  WINE_INFO           VARCHAR(100) NOT NULL COMMENT '와인상세정보',
  WINE_REVIEW         VARCHAR(100) NULL     COMMENT '와인리뷰',
  WINE_FOOD_PAIRING   VARCHAR(100) NOT NULL COMMENT '와인음식페어링',
  PRIMARY KEY (WINE_UID)
) COMMENT '와인';

CREATE TABLE WINE_LIST
(
  WINE_RED_UID VARCHAR(100) NOT NULL COMMENT 'ID',
  NAME         VARCHAR(100) NOT NULL COMMENT '와인 이름',
  WINE_TYPE    VARCHAR(100) NOT NULL COMMENT '와인 종류',
  COUNTRY      VARCHAR(100) NOT NULL COMMENT '나라',
  VARIETY      VARCHAR(100) NOT NULL COMMENT '품종',
  PRICE        VARCHAR(100) NOT NULL COMMENT '가격',
  PRIMARY KEY (WINE_RED_UID)
) COMMENT '와인 목록';

CREATE TABLE WISHLIST
(
  WISHLIST_UID VARCHAR(100) NOT NULL COMMENT 'ID',
  NAME         VARCHAR(100) NOT NULL COMMENT '와인 이름',
  WINE_TYPE    VARCHAR(100) NOT NULL COMMENT '와인 종류',
  COUNTRY      VARCHAR(100) NOT NULL COMMENT '나라',
  VARIETY      VARCHAR(100) NOT NULL COMMENT '품종',
  PRIMARY KEY (WISHLIST_UID)
) COMMENT '위시리스트';