
CREATE TABLE USERS
(
  USER_UID       VARCHAR(100) NOT NULL COMMENT '회원아이디',
  USER_PASSWORD  VARCHAR(100) NOT NULL COMMENT '회원비밀번호',
  USER_NAME      VARCHAR(100) NOT NULL COMMENT '회원이름',
  USER_BIRTH     VARCHAR(100) NOT NULL COMMENT '회원생년월일',
  USER_GENDER    VARCHAR(100) NOT NULL COMMENT '회원성별',
  USER_PHONE     VARCHAR(100) NOT NULL COMMENT '회원전화번호',
  USER_AUTHORITY VARCHAR(100) NOT NULL COMMENT '회원권한',
  PRIMARY KEY (USER_UID)
) COMMENT '회원들';
