
CREATE TABLE COUPON
(
  COUPON_UID          VARCHAR(100) NOT NULL,
  DOWNLOADABLE_COUPON VARCHAR(100) NULL     COMMENT '다운로드 가능한 쿠폰',
  USEABLE_COUPOB      VARCHAR(100) NULL     COMMENT '사용가능한 쿠폰',
  PRIMARY KEY (COUPON_UID)
);
