
CREATE TABLE EVENT
(
  EVENT_UID   VARCHAR(100) NOT NULL COMMENT 'ID',
  EVENT_TITLE VARCHAR(100) NOT NULL COMMENT '이벤트 제목',
  EVENT_DATE  VARCHAR(100) NOT NULL COMMENT '이벤트 날짜',
  PRIMARY KEY (EVENT_UID)
) COMMENT '이벤트';
