
CREATE TABLE EVENT_CONTENT
(
  EVENT_CONTENT_UID VARCHAR(100) NOT NULL COMMENT 'ID',
  EVENT_TITLE       VARCHAR(100) NOT NULL COMMENT '이벤트 제목',
  EVENT_CONTENT     VARCHAR(100) NOT NULL COMMENT '이벤트 내용',
  EVENT_DATE        VARCHAR(100) NOT NULL COMMENT '이벤트 날짜',
  PRIMARY KEY (EVENT_CONTENT_UID)
) COMMENT '이벤트 내용';
