
CREATE TABLE QUESTIONS
(
  QUESTIONS_UID VARCHAR(100) NOT NULL COMMENT 'ID',
  QUESTION      VARCHAR(100) NOT NULL COMMENT '질문',
  ANSWER        VARCHAR(100) NOT NULL COMMENT '답',
  SEARCH        VARCHAR(100) NULL     COMMENT '검색',
  PRIMARY KEY (QUESTIONS_UID)
) COMMENT '자주하는 질문';
