
CREATE TABLE NOTICE_CONTENT
(
  NOTICE_CONTENT_UID VARCHAR(100) NOT NULL COMMENT 'ID',
  NOTICE_TITLE       VARCHAR(100) NOT NULL COMMENT '공지사항 제목',
  NOTICE_CONTENT     VARCHAR(100) NOT NULL COMMENT '공지사항 내용',
  NOTICE_DATE        VARCHAR(100) NOT NULL COMMENT '공지사항 작성일',
  PRIMARY KEY (NOTICE_CONTENT_UID)
) COMMENT '공지사항 내용';
