
CREATE TABLE NOTICE
(
  NOTICE_UID    VARCHAR(100) NOT NULL COMMENT 'ID',
  NOTICE_NO     INT          NOT NULL COMMENT '공지사항 번호',
  NOTICE_TITLE  VARCHAR(100) NOT NULL COMMENT '공지사항 제목',
  NOTICE_DATE   VARCHAR(100) NOT NULL COMMENT '공지사항 작성일',
  NOTICE_SEARCH VARCHAR(100) NULL     COMMENT '공지사항 검색',
  PRIMARY KEY (NOTICE_UID)
) COMMENT '공지사항';
