
CREATE TABLE USER
(
  UNIQUE_ID VARCHAR(100) NOT NULL COMMENT '아이디',
  PASSWORD  VARCHAR(100) NOT NULL COMMENT '비밀번호',
  NAME      VARCHAR(100) NOT NULL COMMENT '이름',
  BIRTH     VARCHAR(100) NOT NULL COMMENT '생년월일',
  GENDER    VARCHAR(100) NOT NULL COMMENT '성별',
  PHONE     VARCHAR(100) NOT NULL COMMENT '전화번호',
  AUTHORITY VARCHAR(100) NOT NULL COMMENT '권한',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '회원';

