
CREATE TABLE USER_REVIEW_MODIFY
(
  URM_UID   VARCHAR(100) NULL     COMMENT '내가작성한리뷰 UID',
  REVIEW_NO VARCHAR(100) NULL     COMMENT '리뷰 번호',
  URM_DATE  VARCHAR(100) NULL     COMMENT '리뷰작성일',
  WINE      VARCHAR(100) NULL     COMMENT '리뷰남긴제품',
  REVIEW    VARCHAR(100) NULL     COMMENT '리뷰'
) COMMENT '내가 작성한 리뷰';
