
CREATE TABLE USER_INQUIRY
(
  USER_INQUIRY_UID         VARCHAR(100) NULL     COMMENT '나의문의내역 UID',
  USER_INQUIRY_NO          VARCHAR(100) NULL     COMMENT '문의내역 번호',
  WINE                     VARCHAR(100) NULL     COMMENT '와인상품정보',
  USER_INQUIRY_TITLE       VARCHAR(100) NULL     COMMENT '문의내역 제목',
  USER_INQUIRY_CONTENT     VARCHAR(100) NULL     COMMENT '문의내역 내용',
  USER_INQUIRY_DATE        VARCHAR(100) NULL     COMMENT '문의내역 등록일',
  USER_INQUIRY_ANSWER      VARCHAR(100) NULL     COMMENT '문의내역 답변',
  USER_INQUIRY_ANSWER_DATE VARCHAR(100) NULL     COMMENT '문의내역처리일'
) COMMENT '나의 문의 내역';
